source "https://rubygems.org"

gem "fluentd", "1.2.2"
gem "oj", "3.5.1"
gem "fluent-plugin-elasticsearch"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "ffi"
gem "fluent-plugin-systemd"
gem "fluent-plugin-concat", "2.1.0"
gem "fluent-plugin-rewrite-tag-filter", "2.1.0"
gem "fluent-plugin-slack", "0.6.7"